# Generated by Django 5.1.3 on 2024-11-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
