# Generated by Django 5.1.3 on 2024-11-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(default="Nepal", max_length=100),
        ),
    ]
