# Generated by Django 5.1.3 on 2024-11-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
